In [1]:
import pandas as pd
from multicor_fa import mcfa_model

In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

### Load in Intersim data

In [4]:
cluster_df = pd.read_csv(
    '../../sim_data/clustering_assignments.tsv', sep='\t', index_col=1
)
cluster_df.head()

          subjects  cluster.id
subject1         1           2
subject2         2           1
subject3         3           5
subject4         4           3
subject5         5           2

In [5]:
exp_data = pd.read_csv('../../sim_data/expression_data.tsv', sep='\t', index_col=0)
methyl_data = pd.read_csv('../../sim_data/methylation_data.tsv', sep='\t', index_col=0)
protein_data = pd.read_csv('../../sim_data/protein_data.tsv', sep='\t', index_col=0)

# Limit to first 1000 samples for now
exp_data = exp_data.iloc[:1000,:]
methyl_data = methyl_data.iloc[:1000,:]
protein_data = protein_data.iloc[:1000,:]
cluster_df = cluster_df.iloc[:1000]

In [6]:
# Create data dictionary
Y = {
    'exp': exp_data, 
    'methyl': methyl_data,
    'prot': protein_data
}

### Fitting model to complete data

In [7]:
for name, df in Y.items():
    print(f"Missing values in {name}:", df.isna().sum().sum())

Missing values in exp: 0
Missing values in methyl: 0
Missing values in prot: 0

In [8]:
print(cluster_df.shape, Y['exp'].shape, Y['methyl'].shape, Y['prot'].shape)

(1000, 2) (1000, 131) (1000, 367) (1000, 160)

In [9]:
%%time
mcfa_res_full = mcfa_model.fit(Y, missing_modes='raise')

Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.
There are 6 components above rho inclusion threshold 1.1972929239273071.
Fitting the model.
iter: 0 Likelihood: 29821.105760421276
Iter: 1 Likelihood: 29097.54813567292 Percent change: 0.024866618361609995 Time (s): 0.00032591819763183594
Iter: 2 Likelihood: 29006.733209858747 Percent change: 0.0031308222527902177 Time (s): 0.0006089210510253906
Iter: 3 Likelihood: 28982.97358877576 Percent change: 0.000819778585182453 Time (s): 0.0008699893951416016
Iter: 4 Likelihood: 28974.306920661005 Percent change: 0.00029911563160029894 Time (s): 0.001127004623413086
Iter: 5 Likelihood: 28970.037121435904 Percent change: 0.00014738673641332973 Time (s): 0.0013887882232666016
Iter: 6 Likelihood: 28967.188647686675 Percent change: 9.833449092604625e-05 Time (s): 0.0016448497772216797
Iter: 7 Likelihood: 28964.933582268906 Percent change: 7.785501773596148e-05 Time (s): 0.0018949508666992188
Iter: 8 Likelihood: 28963.026304770232 Percent change: 6.585214813550907e-05 Time (s): 0.0021331310272216797
Iter: 9 Likelihood: 28961.37485529761 Percent change: 5.702248187017697e-05 Time (s): 0.0023708343505859375
Iter: 10 Likelihood: 28959.930297128754 Percent change: 4.988127229709669e-05 Time (s): 0.002610921859741211
Iter: 11 Likelihood: 28958.658700554366 Percent change: 4.39107552437813e-05 Time (s): 0.002858877182006836
Iter: 12 Likelihood: 28957.533617262477 Percent change: 3.885287009449898e-05 Time (s): 0.003094911575317383
Iter: 13 Likelihood: 28956.533573730816 Percent change: 3.453602376524575e-05 Time (s): 0.0033288002014160156
Iter: 14 Likelihood: 28955.640869212744 Percent change: 3.083007287263565e-05 Time (s): 0.0035638809204101562
Iter: 15 Likelihood: 28954.840795381402 Percent change: 2.763178140042755e-05 Time (s): 0.003796100616455078
Iter: 16 Likelihood: 28954.121054855674 Percent change: 2.4857964928889096e-05 Time (s): 0.0040400028228759766
Iter: 17 Likelihood: 28953.471307986598 Percent change: 2.244106974822981e-05 Time (s): 0.004297018051147461
Iter: 18 Likelihood: 28952.882814473996 Percent change: 2.032590386153948e-05 Time (s): 0.004518985748291016
Iter: 19 Likelihood: 28952.348148033117 Percent change: 1.8467118388643003e-05 Time (s): 0.0047550201416015625
Iter: 20 Likelihood: 28951.860967976983 Percent change: 1.682724494542691e-05 Time (s): 0.00499272346496582
Iter: 21 Likelihood: 28951.415835367206 Percent change: 1.5375158586653413e-05 Time (s): 0.005227804183959961
Iter: 22 Likelihood: 28951.008064216247 Percent change: 1.408486882582503e-05 Time (s): 0.005457878112792969
Iter: 23 Likelihood: 28950.63360039261 Percent change: 1.2934564016926764e-05 Time (s): 0.005700826644897461
Iter: 24 Likelihood: 28950.288922538584 Percent change: 1.1905851957113088e-05 Time (s): 0.005934953689575195
Iter: 25 Likelihood: 28949.970960570605 Percent change: 1.0983153261623602e-05 Time (s): 0.006165742874145508
Iter: 26 Likelihood: 28949.677028306345 Percent change: 1.0153213936453857e-05 Time (s): 0.006390810012817383
Iter: 27 Likelihood: 28949.40476749745 Percent change: 9.404711809511978e-06 Time (s): 0.0066258907318115234
Iter: 28 Likelihood: 28949.152101122985 Percent change: 8.727936955878953e-06 Time (s): 0.00686192512512207
Iter: 29 Likelihood: 28948.917194238133 Percent change: 8.114530960739689e-06 Time (s): 0.007092952728271484
Iter: 30 Likelihood: 28948.69842101698 Percent change: 7.557273144771545e-06 Time (s): 0.00733494758605957
Iter: 31 Likelihood: 28948.494336897278 Percent change: 7.049904472619499e-06 Time (s): 0.007580995559692383
Iter: 32 Likelihood: 28948.303654946423 Percent change: 6.586981853160896e-06 Time (s): 0.007814884185791016
Iter: 33 Likelihood: 28948.125225735093 Percent change: 6.163757063312698e-06 Time (s): 0.008066892623901367
Iter: 34 Likelihood: 28947.95802013679 Percent change: 5.776075749012825e-06 Time (s): 0.008296012878417969
Iter: 35 Likelihood: 28947.801114578822 Percent change: 5.420292800358031e-06 Time (s): 0.008524894714355469
Iter: 36 Likelihood: 28947.653678354014 Percent change: 5.093201212312285e-06 Time (s): 0.008760929107666016
Iter: 37 Likelihood: 28947.514962671135 Percent change: 4.791972059002707e-06 Time (s): 0.008993864059448242
Iter: 38 Likelihood: 28947.384291178012 Percent change: 4.514103651264828e-06 Time (s): 0.009226083755493164
Iter: 39 Likelihood: 28947.26105173612 Percent change: 4.257378329194621e-06 Time (s): 0.009451866149902344
Iter: 40 Likelihood: 28947.144689260196 Percent change: 4.019825691749859e-06 Time (s): 0.009685754776000977
Iter: 41 Likelihood: 28947.034699470423 Percent change: 3.799691088046597e-06 Time (s): 0.009916067123413086
Iter: 42 Likelihood: 28946.930623425982 Percent change: 3.5954086391786808e-06 Time (s): 0.01014399528503418
Iter: 43 Likelihood: 28946.832042730653 Percent change: 3.4055780329620194e-06 Time (s): 0.010371923446655273
Iter: 44 Likelihood: 28946.738575317937 Percent change: 3.2289445138479458e-06 Time (s): 0.010602712631225586
Iter: 45 Likelihood: 28946.64987173735 Percent change: 3.064381577120102e-06 Time (s): 0.010823965072631836
Iter: 46 Likelihood: 28946.565611875067 Percent change: 2.9108759710470236e-06 Time (s): 0.011046886444091797
Iter: 47 Likelihood: 28946.48550205168 Percent change: 2.767514673943135e-06 Time (s): 0.011281967163085938
Iter: 48 Likelihood: 28946.4092724495 Percent change: 2.6334735153037443e-06 Time (s): 0.011509895324707031
Iter: 49 Likelihood: 28946.336674825132 Percent change: 2.5080073234188205e-06 Time (s): 0.01199483871459961
Iter: 50 Likelihood: 28946.267480474973 Percent change: 2.390441192650111e-06 Time (s): 0.012566804885864258
Iter: 51 Likelihood: 28946.20147841949 Percent change: 2.280162926786542e-06 Time (s): 0.012864112854003906
Iter: 52 Likelihood: 28946.138473781717 Percent change: 2.176616332806147e-06 Time (s): 0.013131141662597656
Iter: 53 Likelihood: 28946.078286335018 Percent change: 2.079295374796507e-06 Time (s): 0.013381004333496094
Iter: 54 Likelihood: 28946.02074920231 Percent change: 1.987738943646331e-06 Time (s): 0.013628959655761719
Iter: 55 Likelihood: 28945.965707686857 Percent change: 1.9015263131920857e-06 Time (s): 0.013878822326660156
Iter: 56 Likelihood: 28945.91301822188 Percent change: 1.8202730362755822e-06 Time (s): 0.014114856719970703
Iter: 57 Likelihood: 28945.862547422228 Percent change: 1.7436274206316738e-06 Time (s): 0.01435708999633789
Iter: 58 Likelihood: 28945.81417123131 Percent change: 1.6712672385078434e-06 Time (s): 0.014594793319702148
Iter: 59 Likelihood: 28945.767774148535 Percent change: 1.6028969464150123e-06 Time (s): 0.014837026596069336
Iter: 60 Likelihood: 28945.723248530834 Percent change: 1.5382451258361935e-06 Time (s): 0.01506805419921875
Iter: 61 Likelihood: 28945.680493960062 Percent change: 1.4770622090080204e-06 Time (s): 0.015295028686523438
Iter: 62 Likelihood: 28945.63941666855 Percent change: 1.4191184696809775e-06 Time (s): 0.015531778335571289
Iter: 63 Likelihood: 28945.59992901763 Percent change: 1.3642021936578846e-06 Time (s): 0.01575493812561035
Iter: 64 Likelihood: 28945.56194902293 Percent change: 1.312118063809703e-06 Time (s): 0.01598381996154785
Iter: 65 Likelihood: 28945.52539992207 Percent change: 1.2626856951022997e-06 Time (s): 0.01621389389038086
Iter: 66 Likelihood: 28945.49020978102 Percent change: 1.2157382996580173e-06 Time (s): 0.016444921493530273
Iter: 67 Likelihood: 28945.456311133512 Percent change: 1.1711215447005815e-06 Time (s): 0.01668095588684082
Iter: 68 Likelihood: 28945.423640652632 Percent change: 1.128692441508298e-06 Time (s): 0.016922950744628906
Iter: 69 Likelihood: 28945.392138849427 Percent change: 1.088318411927589e-06 Time (s): 0.017158031463623047
Iter: 70 Likelihood: 28945.36174979749 Percent change: 1.0498763913080154e-06 Time (s): 0.01738595962524414
Iter: 71 Likelihood: 28945.33242087978 Percent change: 1.0132520602400795e-06 Time (s): 0.017612934112548828
Iter: 72 Likelihood: 28945.304102556427 Percent change: 9.783391202620896e-07 Time (s): 0.017845869064331055
Calculating feature importance.
CPU times: user 1.77 s, sys: 834 ms, total: 2.6 s
Wall time: 488 ms

In [10]:
print(
    (mcfa_res_full.W['exp'] @ mcfa_res_full.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.801 -0.064  0.392 -0.213  0.279]
 [-0.064  0.826  0.035 -0.409 -0.381]
 [ 0.392  0.035  0.699 -0.31   0.241]
 [-0.213 -0.409 -0.31   0.65   0.248]
 [ 0.279 -0.381  0.241  0.248  0.546]]

In [11]:
print(
    (mcfa_res_full.L['exp'] @ mcfa_res_full.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [12]:
print(mcfa_res_full.Phi['exp'].round(3))

       0      1      2      3      4      5
0  0.341  0.022 -0.014 -0.005 -0.011 -0.028
1  0.022  0.360  0.013  0.005 -0.038  0.001
2 -0.014  0.013  0.295  0.005 -0.018 -0.030
3 -0.005  0.005  0.005  0.346 -0.021  0.001
4 -0.011 -0.038 -0.018 -0.021  0.363 -0.010
5 -0.028  0.001 -0.030  0.001 -0.010  0.463

### Fitting model to missing data
Each sample missing maximum 1 mode

In [13]:
Y_miss = Y.copy()
Y_miss['exp'] = Y_miss['exp'].iloc[20:]
Y_miss['methyl'] = Y_miss['methyl'].drop(
    index=Y_miss['methyl'].iloc[100:125].index.tolist()
)
Y_miss['prot'] = Y_miss['prot'].drop(
    index=Y_miss['prot'].iloc[500:530].index.tolist()
)

In [14]:
print(cluster_df.shape, Y_miss['exp'].shape, 
      Y_miss['methyl'].shape, Y_miss['prot'].shape)

(1000, 2) (980, 131) (975, 367) (970, 160)

In [15]:
Y['exp'].iloc[15:25, :5]

              ACACA    ACVRL1      AKT1    AKT1S1     ANXA1
subject16  1.239820  1.403926  1.274152  1.615542  1.600042
subject17  0.922452  1.710182 -0.152408  1.469768  2.594138
subject18 -1.026042  0.795188 -0.641408  1.119790  0.905765
subject19  1.873460  1.067464  1.546875  1.908176  1.775778
subject20  1.370386  2.953019  0.185173  0.597633 -0.316857
subject21  1.384600  1.176288  1.172802  1.428453  1.674897
subject22 -0.183378  3.641473  1.145361  0.492304  4.148478
subject23  1.382303  1.795173  0.649608  0.529566  2.785904
subject24  1.073222  3.237707  2.491712 -0.767261  1.677067
subject25  0.681191  1.592903  0.257474  1.673340  3.120252

####  Raise error for missing modes

In [16]:
%%time
# Confirm that missing_modes = raise works
mcfa_res_miss_raise = mcfa_model.fit(Y_miss, missing_modes='raise')

ValueError: Missing modes detected for some samples.

#### Impute mean

In [17]:
mcfa_res_miss_mean = mcfa_model.fit(Y_miss, missing_modes='impute_mean')

Missing modes detected for some samples, Imputing with the mean
Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.

/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:300: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:300: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:300: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(

There are 6 components above rho inclusion threshold 1.1990463733673096.
Fitting the model.
iter: 0 Likelihood: 36969.18813576231
Iter: 1 Likelihood: 36427.8905981005 Percent change: 0.01485942580737952 Time (s): 0.00030803680419921875
Iter: 2 Likelihood: 36386.859660412934 Percent change: 0.0011276306356331764 Time (s): 0.0005779266357421875
Iter: 3 Likelihood: 36381.17224584261 Percent change: 0.00015632851332809502 Time (s): 0.0008320808410644531
Iter: 4 Likelihood: 36379.41091307724 Percent change: 4.841564833404083e-05 Time (s): 0.0010709762573242188
Iter: 5 Likelihood: 36378.465375257365 Percent change: 2.5991690691807976e-05 Time (s): 0.0013079643249511719
Iter: 6 Likelihood: 36377.83612752619 Percent change: 1.729755802315351e-05 Time (s): 0.0015430450439453125
Iter: 7 Likelihood: 36377.382988083016 Percent change: 1.245662568207524e-05 Time (s): 0.0017910003662109375
Iter: 8 Likelihood: 36377.04510701173 Percent change: 9.28830448694624e-06 Time (s): 0.0020220279693603516
Iter: 9 Likelihood: 36376.78823038952 Percent change: 7.061553114127309e-06 Time (s): 0.0022649765014648438
Iter: 10 Likelihood: 36376.59031467578 Percent change: 5.440743951735945e-06 Time (s): 0.002774953842163086
Iter: 11 Likelihood: 36376.436207915656 Percent change: 4.236444692939239e-06 Time (s): 0.0033791065216064453
Iter: 12 Likelihood: 36376.31512687747 Percent change: 3.328567991746385e-06 Time (s): 0.0038847923278808594
Iter: 13 Likelihood: 36376.21923138563 Percent change: 2.6362138194946606e-06 Time (s): 0.004199028015136719
Iter: 14 Likelihood: 36376.142731867585 Percent change: 2.1030134670216657e-06 Time (s): 0.004477024078369141
Iter: 15 Likelihood: 36376.08129880661 Percent change: 1.6888311984589848e-06 Time (s): 0.0047550201416015625
Iter: 16 Likelihood: 36376.031659256434 Percent change: 1.3646224701174547e-06 Time (s): 0.005014896392822266
Iter: 17 Likelihood: 36375.99131520892 Percent change: 1.109084482765679e-06 Time (s): 0.005261898040771484
Iter: 18 Likelihood: 36375.95834374859 Percent change: 9.064080186417997e-07 Time (s): 0.005507946014404297
Calculating feature importance.

In [18]:
print(
    (mcfa_res_miss_mean.W['exp'] @ mcfa_res_miss_mean.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.799 -0.068  0.397 -0.223  0.281]
 [-0.068  0.815  0.048 -0.408 -0.373]
 [ 0.397  0.048  0.69  -0.317  0.233]
 [-0.223 -0.408 -0.317  0.65   0.244]
 [ 0.281 -0.373  0.233  0.244  0.539]]

In [19]:
print(
    (mcfa_res_miss_mean.L['exp'] @ mcfa_res_miss_mean.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [20]:
print(mcfa_res_miss_mean.Phi['exp'].round(3))

       0      1      2      3      4      5
0  0.812 -0.067 -0.013  0.143 -0.076  0.016
1 -0.067  0.451 -0.003 -0.062  0.081  0.002
2 -0.013 -0.003  0.523  0.096 -0.067 -0.017
3  0.143 -0.062  0.096  0.666 -0.212 -0.025
4 -0.076  0.081 -0.067 -0.212  0.568 -0.040
5  0.016  0.002 -0.017 -0.025 -0.040  0.548

#### Drop samples with missing data

In [21]:
mcfa_res_miss_drop = mcfa_model.fit(Y_miss, missing_modes='drop')

Missing modes detected for some samples, dropping sampleswith missing modes. There are 925 samples remaining.
Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.
There are 6 components above rho inclusion threshold 1.2059963941574097.
Fitting the model.
iter: 0 Likelihood: 27592.75104490256
Iter: 1 Likelihood: 26924.338111388388 Percent change: 0.024825603167992077 Time (s): 0.0002892017364501953
Iter: 2 Likelihood: 26840.19408552931 Percent change: 0.0031350006483165855 Time (s): 0.0005502700805664062
Iter: 3 Likelihood: 26818.06986688629 Percent change: 0.0008249743084732144 Time (s): 0.00081634521484375
Iter: 4 Likelihood: 26809.986973990333 Percent change: 0.0003014881321575399 Time (s): 0.001062154769897461
Iter: 5 Likelihood: 26806.016720093805 Percent change: 0.0001481105506269547 Time (s): 0.0013072490692138672
Iter: 6 Likelihood: 26803.38044479827 Percent change: 9.835607493483976e-05 Time (s): 0.0015411376953125
Iter: 7 Likelihood: 26801.300160673654 Percent change: 7.761877640799881e-05 Time (s): 0.0017812252044677734
Iter: 8 Likelihood: 26799.543681236886 Percent change: 6.554139345282555e-05 Time (s): 0.002035379409790039
Iter: 9 Likelihood: 26798.023973428262 Percent change: 5.670969658549487e-05 Time (s): 0.0022821426391601562
Iter: 10 Likelihood: 26796.695022223917 Percent change: 4.9593847421952825e-05 Time (s): 0.0025200843811035156
Iter: 11 Likelihood: 26795.525190993485 Percent change: 4.365770859477941e-05 Time (s): 0.0027561187744140625
Iter: 12 Likelihood: 26794.4899691612 Percent change: 3.86356237224753e-05 Time (s): 0.0030002593994140625
Iter: 13 Likelihood: 26793.569533976657 Percent change: 3.4352839153310796e-05 Time (s): 0.003233194351196289
Iter: 14 Likelihood: 26792.7475872586 Percent change: 3.0677955494489354e-05 Time (s): 0.0034942626953125
Iter: 15 Likelihood: 26792.010610208086 Percent change: 2.7507343933083452e-05 Time (s): 0.003725290298461914
Iter: 16 Likelihood: 26791.347314459705 Percent change: 2.4757834706717106e-05 Time (s): 0.0039632320404052734
Iter: 17 Likelihood: 26790.748217586402 Percent change: 2.2362080686828997e-05 Time (s): 0.004205226898193359
Iter: 18 Likelihood: 26790.205309273762 Percent change: 2.026517924639163e-05 Time (s): 0.00443720817565918
Iter: 19 Likelihood: 26789.71178662743 Percent change: 1.8422096148776343e-05 Time (s): 0.004669189453125
Iter: 20 Likelihood: 26789.26184295623 Percent change: 1.6795672603339748e-05 Time (s): 0.004900217056274414
Iter: 21 Likelihood: 26788.850498202213 Percent change: 1.535507296388495e-05 Time (s): 0.0051462650299072266
Iter: 22 Likelihood: 26788.473461986578 Percent change: 1.4074568906310439e-05 Time (s): 0.005376100540161133
Iter: 23 Likelihood: 26788.12702234186 Percent change: 1.2932581827285582e-05 Time (s): 0.005605220794677734
Iter: 24 Likelihood: 26787.807954794174 Percent change: 1.1910924112402101e-05 Time (s): 0.005834102630615234
Iter: 25 Likelihood: 26787.513447664685 Percent change: 1.0994194368368865e-05 Time (s): 0.00606226921081543
Iter: 26 Likelihood: 26787.241040371027 Percent change: 1.0169292658676173e-05 Time (s): 0.006291389465332031
Iter: 27 Likelihood: 26786.988572211707 Percent change: 9.425029567613303e-06 Time (s): 0.006525278091430664
Iter: 28 Likelihood: 26786.754139647015 Percent change: 8.751809325969508e-06 Time (s): 0.006758213043212891
Iter: 29 Likelihood: 26786.53606050564 Percent change: 8.141371504000843e-06 Time (s): 0.006989240646362305
Iter: 30 Likelihood: 26786.33284386238 Percent change: 7.586579486127874e-06 Time (s): 0.007224082946777344
Iter: 31 Likelihood: 26786.143164585792 Percent change: 7.0812462780453286e-06 Time (s): 0.007462263107299805
Iter: 32 Likelihood: 26785.96584174396 Percent change: 6.619990590562851e-06 Time (s): 0.007692098617553711
Iter: 33 Likelihood: 26785.799820217606 Percent change: 6.198117191530969e-06 Time (s): 0.007921218872070312
Iter: 34 Likelihood: 26785.64415498596 Percent change: 5.811517197271957e-06 Time (s): 0.008159399032592773
Iter: 35 Likelihood: 26785.497997651863 Percent change: 5.456584533520909e-06 Time (s): 0.00838923454284668
Iter: 36 Likelihood: 26785.360584848422 Percent change: 5.130145737821938e-06 Time (s): 0.008614301681518555
Iter: 37 Likelihood: 26785.231228233763 Percent change: 4.829400708076603e-06 Time (s): 0.008838176727294922
Iter: 38 Likelihood: 26785.10930583001 Percent change: 4.551872548293591e-06 Time (s): 0.009063243865966797
Iter: 39 Likelihood: 26784.994254504312 Percent change: 4.295364957140401e-06 Time (s): 0.009294271469116211
Iter: 40 Likelihood: 26784.885563423173 Percent change: 4.0579259105567945e-06 Time (s): 0.009537220001220703
Iter: 41 Likelihood: 26784.78276833964 Percent change: 3.837816585007132e-06 Time (s): 0.009779214859008789
Iter: 42 Likelihood: 26784.68544659305 Percent change: 3.633484768182338e-06 Time (s): 0.010010242462158203
Iter: 43 Likelihood: 26784.593212723525 Percent change: 3.443541919457298e-06 Time (s): 0.010242223739624023
Iter: 44 Likelihood: 26784.50571461589 Percent change: 3.2667434137592742e-06 Time (s): 0.01047825813293457
Iter: 45 Likelihood: 26784.42263009973 Percent change: 3.1019715193857945e-06 Time (s): 0.010705232620239258
Iter: 46 Likelihood: 26784.34366394793 Percent change: 2.94822052726046e-06 Time (s): 0.010938167572021484
Iter: 47 Likelihood: 26784.268545219224 Percent change: 2.804583913844087e-06 Time (s): 0.011178016662597656
Iter: 48 Likelihood: 26784.197024901347 Percent change: 2.670243121737414e-06 Time (s): 0.011404037475585938
Iter: 49 Likelihood: 26784.128873815902 Percent change: 2.5444577931119977e-06 Time (s): 0.011638164520263672
Iter: 50 Likelihood: 26784.06388075347 Percent change: 2.426557176710427e-06 Time (s): 0.011862039566040039
Iter: 51 Likelihood: 26784.001850809353 Percent change: 2.315932640069333e-06 Time (s): 0.012087106704711914
Iter: 52 Likelihood: 26783.9426038968 Percent change: 2.212031045149281e-06 Time (s): 0.01231527328491211
Iter: 53 Likelihood: 26783.885973415054 Percent change: 2.1143489710108154e-06 Time (s): 0.01254129409790039
Iter: 54 Likelihood: 26783.83180505602 Percent change: 2.0224275387024597e-06 Time (s): 0.012790203094482422
Iter: 55 Likelihood: 26783.7799557312 Percent change: 1.935847923846675e-06 Time (s): 0.01301121711730957
Iter: 56 Likelihood: 26783.73029260689 Percent change: 1.8542273150580352e-06 Time (s): 0.013297319412231445
Iter: 57 Likelihood: 26783.682692235176 Percent change: 1.7772153390099786e-06 Time (s): 0.013615131378173828
Iter: 58 Likelihood: 26783.637039767975 Percent change: 1.7044909596507952e-06 Time (s): 0.013886213302612305
Iter: 59 Likelihood: 26783.593228249072 Percent change: 1.635759568527529e-06 Time (s): 0.014144182205200195
Iter: 60 Likelihood: 26783.551157971495 Percent change: 1.5707505449580375e-06 Time (s): 0.014400005340576172
Iter: 61 Likelihood: 26783.510735895743 Percent change: 1.5092149849375183e-06 Time (s): 0.014633417129516602
Iter: 62 Likelihood: 26783.471875122133 Percent change: 1.45092368124169e-06 Time (s): 0.014879465103149414
Iter: 63 Likelihood: 26783.43449441053 Percent change: 1.3956653547394707e-06 Time (s): 0.015127182006835938
Iter: 64 Likelihood: 26783.398517743804 Percent change: 1.3432450217426682e-06 Time (s): 0.015368223190307617
Iter: 65 Likelihood: 26783.36387393023 Percent change: 1.2934825415460174e-06 Time (s): 0.015609264373779297
Iter: 66 Likelihood: 26783.330496240073 Percent change: 1.2462113388681415e-06 Time (s): 0.01585221290588379
Iter: 67 Likelihood: 26783.298322074912 Percent change: 1.2012771830280005e-06 Time (s): 0.016089200973510742
Iter: 68 Likelihood: 26783.26729266397 Percent change: 1.1585371792518497e-06 Time (s): 0.016324281692504883
Iter: 69 Likelihood: 26783.237352786844 Percent change: 1.1178587835836085e-06 Time (s): 0.016555070877075195
Iter: 70 Likelihood: 26783.208450519614 Percent change: 1.0791189294204203e-06 Time (s): 0.016791105270385742
Iter: 71 Likelihood: 26783.180537001233 Percent change: 1.0422032716537526e-06 Time (s): 0.017029285430908203
Iter: 72 Likelihood: 26783.153566219695 Percent change: 1.0070054473611596e-06 Time (s): 0.017342329025268555
Iter: 73 Likelihood: 26783.127494814675 Percent change: 9.734264613083446e-07 Time (s): 0.017643213272094727
Calculating feature importance.

In [22]:
print(
    (mcfa_res_miss_drop.W['exp'] @ mcfa_res_miss_drop.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.807 -0.063  0.4   -0.223  0.277]
 [-0.063  0.828  0.05  -0.399 -0.367]
 [ 0.4    0.05   0.696 -0.325  0.233]
 [-0.223 -0.399 -0.325  0.652  0.239]
 [ 0.277 -0.367  0.233  0.239  0.542]]

In [23]:
print(
    (mcfa_res_miss_drop.L['exp'] @ mcfa_res_miss_drop.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [24]:
print(mcfa_res_miss_drop.Phi['exp'].round(3))

       0      1      2      3      4      5
0  0.339  0.023  0.015 -0.001  0.006  0.027
1  0.023  0.364 -0.007 -0.002  0.046 -0.004
2  0.015 -0.007  0.295 -0.001 -0.019 -0.031
3 -0.001 -0.002 -0.001  0.336  0.022  0.007
4  0.006  0.046 -0.019  0.022  0.368 -0.011
5  0.027 -0.004 -0.031  0.007 -0.011  0.463

### Impute model

In [25]:
%%time
mcfa_res_miss_impute = mcfa_model.fit(Y_miss, missing_modes='impute_model')

Missing modes detected in input, they will be imputed duringmodel fitting.
Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.

/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(

There are 6 components above rho inclusion threshold 1.2023662328720093.
Fitting the model.
iter: 0 Likelihood: 38349.40622680884
Iter: 1 Likelihood: 37161.07849375623 Percent change: 0.03197775148674096 Time (s): 0.0006859302520751953
Iter: 2 Likelihood: 37898.92344643566 Percent change: -0.019468757568332166 Time (s): 0.0019159317016601562
Calculating feature importance.
CPU times: user 1.87 s, sys: 1.02 s, total: 2.89 s
Wall time: 579 ms

In [26]:
print(
    (mcfa_res_miss_impute.W['exp'] @ mcfa_res_miss_impute.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.832 -0.071  0.405 -0.224  0.288]
 [-0.071  0.865  0.038 -0.421 -0.401]
 [ 0.405  0.038  0.73  -0.329  0.251]
 [-0.224 -0.421 -0.329  0.677  0.254]
 [ 0.288 -0.401  0.251  0.254  0.572]]

In [27]:
print(
    (mcfa_res_miss_impute.L['exp'] @ mcfa_res_miss_impute.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [28]:
print(mcfa_res_miss_impute.Phi['exp'].round(3))

       0      1      2      3      4      5
0  0.548  0.044  0.014  0.028 -0.009  0.014
1  0.044  0.420  0.009 -0.028  0.042 -0.017
2  0.014  0.009  0.389  0.017 -0.025 -0.043
3  0.028 -0.028  0.017  0.381 -0.057 -0.000
4 -0.009  0.042 -0.025 -0.057  0.386  0.008
5  0.014 -0.017 -0.043 -0.000  0.008  0.416

Each sample missing up to 2 modes

In [29]:
Y_miss_2 = Y.copy()
Y_miss_2['exp'] = Y_miss_2['exp'].drop(
    index=Y_miss_2['exp'].iloc[100:175].index.tolist()
)
Y_miss_2['methyl'] = Y_miss_2['methyl'].drop(
    index=Y_miss_2['methyl'].iloc[150:200].index.tolist()
)
Y_miss_2['prot'] = Y_miss_2['prot'].drop(
    index=Y_miss_2['prot'].iloc[190:225].index.tolist()
)

In [30]:
%%time
mcfa_res_miss_impute_2 = mcfa_model.fit(Y_miss_2, missing_modes='impute_model')

Missing modes detected in input, they will be imputed duringmodel fitting.
Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.

/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(

There are 6 components above rho inclusion threshold 1.2139308452606201.
Fitting the model.
iter: 0 Likelihood: 40672.35379489782
Iter: 1 Likelihood: 39427.88900918834 Percent change: 0.03156305896619194 Time (s): 0.001508951187133789
Iter: 2 Likelihood: 40302.85646255063 Percent change: -0.021709812409334193 Time (s): 0.0023620128631591797
Calculating feature importance.
CPU times: user 1.82 s, sys: 1.01 s, total: 2.83 s
Wall time: 572 ms

In [31]:
print(
    (mcfa_res_miss_impute_2.W['exp'] @ mcfa_res_miss_impute_2.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.834 -0.064  0.412 -0.231  0.285]
 [-0.064  0.863  0.035 -0.422 -0.393]
 [ 0.412  0.035  0.727 -0.335  0.242]
 [-0.231 -0.422 -0.335  0.682  0.255]
 [ 0.285 -0.393  0.242  0.255  0.568]]

In [32]:
print(
    (mcfa_res_miss_impute_2.L['exp'] @ mcfa_res_miss_impute_2.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [33]:
print(mcfa_res_miss_impute_2.Phi['exp'].round(3))

       0      1      2      3      4      5
0  0.542  0.014  0.006 -0.000  0.019 -0.027
1  0.014  0.416 -0.014 -0.001 -0.020  0.022
2  0.006 -0.014  0.506  0.060  0.066 -0.045
3 -0.000 -0.001  0.060  0.364  0.009  0.005
4  0.019 -0.020  0.066  0.009  0.331  0.001
5 -0.027  0.022 -0.045  0.005  0.001  0.341

Larger blocks of missing data

In [34]:
Y_miss_3 = Y.copy()
Y_miss_3['exp'] = Y_miss_3['exp'].iloc[150:]
Y_miss_3['methyl'] = Y_miss_3['methyl'].drop(
    index=Y_miss_3['methyl'].iloc[120:420].index.tolist()
)
Y_miss_3['prot'] = Y_miss_3['prot'].drop(
    index=Y_miss_3['prot'].iloc[350:550].index.tolist()
)

In [35]:
%%time
mcfa_res_miss_impute_3 = mcfa_model.fit(Y_miss_3, missing_modes='impute_model')

Missing modes detected in input, they will be imputed duringmodel fitting.
Calculating data PCs.
Calculating empirical covariance.
Initializing model.
Inferring the shared dimensionality.

/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(
/Users/zsxie/Documents/Brown Lab Rotation/code/MCFA/src/multicor_fa/mcfa_model.py:310: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  Y = [pd.concat([Y_m, pd.DataFrame(

There are 6 components above rho inclusion threshold 1.2941317558288574.
Fitting the model.
iter: 0 Likelihood: 53723.123551776465
Iter: 1 Likelihood: 62893.62288130573 Percent change: -0.1458096848202884 Time (s): 0.0007739067077636719
Calculating feature importance.
CPU times: user 1.37 s, sys: 641 ms, total: 2.01 s
Wall time: 498 ms

In [36]:
print(
    (mcfa_res_miss_impute_3.W['exp'] @ mcfa_res_miss_impute_3.W['exp'].T).values[:5,:5].round(3)
)

[[ 0.908 -0.079  0.445 -0.264  0.298]
 [-0.079  0.928  0.038 -0.441 -0.43 ]
 [ 0.445  0.038  0.785 -0.374  0.262]
 [-0.264 -0.441 -0.374  0.726  0.274]
 [ 0.298 -0.43   0.262  0.274  0.623]]

In [37]:
print(
    (mcfa_res_miss_impute_3.L['exp'] @ mcfa_res_miss_impute_3.L['exp'].T).values[:5,:5].round(3)
)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [38]:
print(mcfa_res_miss_impute_3.Phi['exp'].round(3))

       0      1      2      3      4      5
0  3.153  0.020  0.001 -0.044 -0.001 -0.001
1  0.020  2.102 -0.010  0.036  0.040  0.003
2  0.001 -0.010  1.777 -0.047  0.012 -0.028
3 -0.044  0.036 -0.047  1.284  0.011  0.016
4 -0.001  0.040  0.012  0.011  1.121  0.014
5 -0.001  0.003 -0.028  0.016  0.014  0.823